const asmaAlHusna = [
  {name:"الرَّحْمَٰن", meaning:"ذو الرحمة الواسعة التي شملت جميع الخلق", audio:"alrahman.mp3"},
  {name:"الرَّحِيم", meaning:"ذو الرحمة الخاصة بالمؤمنين يوم القيامة", audio: "alrahem.mp3"},
  {name:"الْمَلِك", meaning:"المالك لكل شيء المتصرف فيه بلا منازع", audio: "almalk.mp3"},
  {name:"الْقُدُّوس", meaning:"المنزّه عن كل نقص وعيب", audio: "alkodos.mp3"},
  {name:"السَّلَام", meaning:"السالم من كل عيب ونقص، ومصدر السلامة لعباده", audio: "alsalam.mp3"},
  {name:"الْمُؤْمِن", meaning:"الذي يصدق عباده وعده، ويؤمّن الخائفين", audio: "almoamn.mp3"},
  {name:"الْمُهَيْمِن", meaning:"الرقيب الحافظ لكل شيء",audio: "almohimen.mp3"},
  {name:"الْعَزِيز", meaning:"الغالب القوي الذي لا يُغلب",audio: "al3azez.mp3"},
  {name:"الْجَبَّار", meaning:"الذي يجبر الضعيف ويقهر الجبابرة",audio: "algabar.mp3"},
  {name:"الْمُتَكَبِّر", meaning:"العظيم المتفرد بالكبرياء والعظمة",audio: "almtakbr.mp3"},
  {name:"الْخَالِق", meaning:"الذي أوجد الأشياء من العدم",audio:"alkhalk.mp3"},
  {name:"الْبَارِئ", meaning:"الذي خلق الخلق بلا مثال سابق",audio:"albarea.mp3"},
  {name:"الْمُصَوِّر", meaning:"الذي صوّر جميع المخلوقات بصور مختلفة",audio:"almosawr.mp3"},
  {name:"الْغَفَّار", meaning:"كثير المغفرة لذنوب عباده",audio:"alkfar.mp3"},
  {name:"الْقَهَّار", meaning:"الغالب لكل شيء القاهر لكل مخلوق",audio:"alkhar.mp3"},
  {name:"الْوَهَّاب", meaning:"كثير العطاء بلا مقابل",audio:"alwhap.mp3"},
  {name:"الرَّزَّاق", meaning:"الذي يرزق جميع خلقه",audio:"alrzak.mp3"},
  {name:"الْفَتَّاح", meaning:"الذي يفتح أبواب الرحمة والرزق لعباده",audio:"alftah.mp3"},
  {name:"اَلْعَلِيمُ", meaning:"العالم بكل شيء ظاهره وباطنه",audio:"al3alem.mp3"},
  {name:"الْقَابِض", meaning:"الذي يقبض الأرزاق والأرواح بحكمته",audio:"alkapd.mp3"},
  {name:"الْبَاسِط", meaning:"الذي يبسط الرزق لمن يشاء",audio:"alpast.mp3"},
  {name:"الْخَافِض", meaning:"الذي يخفض من يشاء بعدله",audio:"alkhaft.mp3"},
  {name:"الرَّافِع", meaning:"الذي يرفع من يشاء بفضله",audio:"alraf3.mp3"},
  {name:"الْمُعِزّ", meaning:"الذي يهب العزة لمن يشاء",audio:"almo3z.mp3"},
  {name:"المُذِلّ", meaning:"الذي يذل من يشاء بعدله وحكمته",audio:"almozl.mp3"},
  {name:"السَّمِيع", meaning:"الذي يسمع كل شيء ولو خفي",audio:"alsame3.mp3"},
  {name:"الْبَصِير", meaning:"الذي يرى كل شيء ولو دق",audio:"albaser.mp3"},
  {name:"الْحَكَم", meaning:"الحاكم العادل الفاصل بين الخلق",audio:"alhkm.mp3"},
  {name:"الْعَدْل", meaning:"المنزه عن الظلم والجور",audio:"al3dl.mp3"},
  {name:"اللَّطِيف", meaning:"الرفيق بعباده العالم بدقائق الأمور",audio:"alatef.mp3"},
  {name:"الْخَبِير", meaning:"العالم ببواطن الأمور وخفاياها",audio:"alkhaber.mp3"},
  {name:"الْحَلِيم", meaning:"الذي لا يعاجل بالعقوبة مع قدرته عليها",audio:"alhalem.mp3"},
  {name:"الْعَظِيم", meaning:"ذو العظمة والكبرياء المطلقة",audio:"al3azem.mp3"},
  {name:"الْغَفُور", meaning:"الساتر للذنوب والمتجاوز عنها",audio:"al3afor.mp3"},
  {name:"الشَّكُور", meaning:"الذي يثيب على القليل من الطاعة بالكثير من الثواب",audio:"alshakor.mp3"},
  {name:"الْعَلِيّ", meaning:"المرتفع فوق خلقه بذاته وقدره",audio:"al3ley.mp3"},
  {name:"الْكَبِير", meaning:"العظيم الذي لا أعظم منه",audio:"alkaper.mp3"},
  {name:"الْحَفِيظ", meaning:"الذي يحفظ خلقه ويحفظ أعمالهم",audio:"alhafez.mp3"},
  {name:"المُقيت", meaning:"المقتدر، وقيل الذي يعطي أقوات الخلائق",audio:"almoket.mp3"},
  {name:"الْحسِيب", meaning:"الكافي عباده، المحاسب لهم على أعمالهم",audio:"alhasep.mp3"},
  {name:"الْجَلِيل", meaning:"ذو الجلال والعظمة والكمال",audio:"algalel.mp3"},
  {name:"الْكَرِيم", meaning:"كثير الخير والعطاء الجواد الذي لا ينفد عطاؤه",audio:"alkarem.mp3"},
  {name:"الرَّقِيب", meaning:"المطّلع على خلقه لا يغفل عنهم",audio:"alrakep.mp3"},
  {name:"الْمُجِيب", meaning:"الذي يجيب دعاء من دعاه",audio:"almogep.mp3"},
  {name:"الْوَاسِع", meaning:"الواسع الفضل والرحمة والعلم",audio:"alwas3.mp3"},
  {name:"الْحَكِيم", meaning:"صاحب الحكمة في خلقه وأمره",audio:"alhakem.mp3"},
  {name:"الْوَدُود", meaning:"المحب لأوليائه المحبوب في قلوب عباده الصالحين",audio:"alwadod.mp3"},
  {name:"الْمَجِيد", meaning:"ذو المجد والشرف والعظمة",audio:"almoged.mp3"},
  {name:"الْبَاعِث", meaning:"الذي يبعث الخلق يوم القيامة",audio:"alba3th.mp3"},
  {name:"الشَّهِيد", meaning:"المطّلع على كل شيء لا يغيب عنه شيء",audio:"alshahed.mp3"},
  {name:"الْحَقّ", meaning:"الثابت الذي لا يزول، المتحقق وجوده",audio:"al3hk.mp3"},
  {name:"الْوَكِيل", meaning:"الذي يتولى أمور عباده ويكفيهم",audio:"alwakel.mp3"},
  {name:"الْقَوِيّ", meaning:"كامل القوة والقدرة",audio:"alqwe.mp3"},
  {name:"الْمَتِين", meaning:"شديد القوة الذي لا يلحقه تعب",audio:"almaten.mp3"},
  {name:"الْوَلِيّ", meaning:"الناصر المحب لعباده المؤمنين",audio:"alwly.mp3"},
  {name:"الْحَمِيد", meaning:"المستحق للحمد على كل حال",audio:"alhamed.mp3"},
  {name:"الْمُحْصِي", meaning:"الذي أحصى كل شيء علمًا وعددًا",audio:"almohse.mp3"},
  {name:"الْمُبْدِئ", meaning:"الذي بدأ الخلق من العدم",audio:"almobdey.mp3"},
  {name:"الْمُعِيد", meaning:"الذي يعيد الخلق بعد الموت",audio:"almo3ed.mp3"},
  {name:"الْمُحْيِي", meaning:"الذي يهب الحياة لمن يشاء",audio:"almohye.mp3"},
  {name:"اَلْمُمِيتُ", meaning:"الذي يقدّر الموت على من يشاء",audio:"almomet.mp3"},
  {name:"الْحَيّ", meaning:"الدائم الحياة الذي لا يموت",audio:"alhay.mp3"},
  {name:"الْقَيُّوم", meaning:"القائم بذاته المقيم لغيره",audio:"alqayom.mp3"},
  {name:"الْوَاجِد", meaning:"الغني الذي لا يفتقر لشيء",audio:"alwaged.mp3"},
  {name:"الْمَاجِد", meaning:"ذو المجد والكرم الواسع",audio:"almaged.mp3"},
  {name:"الْواحِد", meaning:"المتفرد في ذاته وصفاته لا شريك له",audio:"alwahed.mp3"},
  {name:"اَلاَحَد", meaning:"الفرد الذي لا نظير له ولا شبيه",audio:"alahd.mp3"},
  {name:"الصَّمَد", meaning:"الذي تصمد إليه الخلائق في حوائجها",audio:"alsamd.mp3"},
  {name:"الْقَادِر", meaning:"القادر على كل شيء",audio:"alkader.mp3"},
  {name:"الْمُقْتَدِر", meaning:"كامل القدرة الذي لا يعجزه شيء",audio:"almoktadr.mp3"},
  {name:"الْمُقَدِّم", meaning:"الذي يقدّم من يشاء بفضله",audio:"almokadm.mp3"},
  {name:"الْمُؤَخِّر", meaning:"الذي يؤخر من يشاء بحكمته",audio:"almoakher.mp3"},
  {name:"الأوَّل", meaning:"الذي ليس قبله شيء",audio:"alawl.mp3"},
  {name:"الآخِر", meaning:"الذي ليس بعده شيء",audio:"alakher.mp3"},
  {name:"الظَّاهِر", meaning:"الغالب العالي فوق كل شيء بأدلة وجوده الظاهرة",audio:"alzher.mp3"},
  {name:"الْبَاطِن", meaning:"العالم بكل خفي، المحتجب عن إدراك الأبصار",audio:"albaten.mp3"},
  {name:"الْوَالِي", meaning:"المالك لتدبير الأمور كلها",audio:"elwalee.mp3"},
  {name:"الْمُتَعَالِي", meaning:"المنزه عن صفات الخلق وسمات النقص",audio:"almota3ale.mp3"},
  {name:"الْبَرّ", meaning:"المحسن إلى خلقه اللطيف بهم",audio:"albrr.mp3"},
  {name:"التَّوَّاب", meaning:"الذي يقبل توبة عباده ويعينهم عليها",audio:"altwap.mp3"},
  {name:"الْمُنْتَقِم", meaning:"الذي ينتقم من الظالمين والعصاة إذا شاء",audio:"almontakm.mp3"},
  {name:"العَفُوّ", meaning:"الذي يمحو الذنوب ويتجاوز عن السيئات",audio:"alfoo.mp3"},
  {name:"الرَّؤُوف", meaning:"شديد الرحمة والرأفة بعباده",audio:"alraof.mp3"},
  {name:"مَالِكُ الْمُلْك", meaning:"المتصرف في الملك كله يعطيه من يشاء ويسلبه ممن يشاء",audio:"malkalmolk.mp3"},
  {name:"ذُوالْجَلاَلِ وَالإكْرَام", meaning:"صاحب العظمة والكرم المطلق",audio:"zoalgalal.mp3"},
  {name:"الْمُقْسِط", meaning:"العادل في أحكامه وقضائه",audio:"almokast.mp3"},
  {name:"الْجَامِع", meaning:"الذي يجمع الخلائق ليوم لا ريب فيه",audio:"algame3.mp3"},
  {name:"الْغَنِيّ", meaning:"الغني عن كل ما سواه المستغني بذاته",audio:"alkhany.mp3"},
  {name:"الْمُغْنِي", meaning:"الذي يغني من يشاء من عباده",audio:"almokhny.mp3"},
  {name:"اَلْمَانِعُ", meaning:"الذي يمنع عن عباده ما يشاء بحكمته",audio:"alman3.mp3"},
  {name:"الضَّار", meaning:"الذي يقدّر الضرر بحكمته لمن يشاء",audio:"aldar.mp3"},
  {name:"النَّافِع", meaning:"الذي يوصل النفع لمن يشاء من عباده",audio:"alnaf3.mp3"},
  {name:"النُّور", meaning:"منوّر السماوات والأرض، هادي القلوب",audio:"alnoor.mp3"},
  {name:"الْهَادِي", meaning:"الذي يهدي عباده إلى الصراط المستقيم",audio:"alhadey.mp3"},
  {name:"الْبَدِيع", meaning:"الذي أبدع الخلق على غير مثال سابق",audio:"albadee4.mp3"},
  {name:"اَلْبَاقِي", meaning:"الدائم الذي لا يفنى ولا يزول",audio:"albakyy.mp3"},
  {name:"الْوَارِث", meaning:"الباقي بعد فناء الخلق، الذي يرث الأرض ومن عليها",audio:"alwares.mp3"},
  {name:"الرَّشِيد", meaning:"الذي يرشد الخلق إلى مصالحهم",audio:"alrashed.mp3"},
  {name:"الصَّبُور", meaning:"الذي لا يعاجل العصاة بالعقوبة، ويمهلهم بحلمه",audio:"alsabor.mp3"}
];
